### ISSUE TITLE
Integrate bootstrap confidence intervals for diversity stats

### ISSUE THREAD

**Issue by zkamvar** [grunwaldlab/poppr#10]
## Introduction

The `poppr` command returns a table that contains diversity summary statistics and linkage summary statistics. Currently, the only summary statistics that give a level of confidence are rarefaction (`eMLG`) and linkage (`Ia` and `rbarD`). It only makes sense to provide confidence intervals or standard errors for the other diversity statistics present in the diversity table.

## Current implementation

A working example can be found [in this bit of code.](https://github.com/zkamvar/Sudden_Oak_Death_in_Oregon_Forests/blob/master/PramCurry/R/allFunctions.R#L907-L956) It performs bootstrapping using the boot package and returns confidence intervals. Since it uses the boot package, it has inherent multicore functionality. 

## Tasks

- [x] integrate bootstrapping for summary statistics
- [ ] allow users to select confidence intervals or standard errors
- [x] add option to keep or remove analyses from the table
- [x] document function

**Comment by zkamvar** [comment]
This might be better implemented in a brand new function that will allow users to specify the columns of output, while deprecating the poppr function.

**Comment by zkamvar** [comment]
This is currently stalled due to questions of proper methods for centering confidence intervals around the observed data. [I asked a question here](http://stats.stackexchange.com/questions/156235/biased-bootstrap-is-it-okay-to-center-the-ci-around-the-observed-statistic), but have yet to get a response.
