### ISSUE TITLE
Add euclidean distance calculation option for bitwise.dist

### ISSUE THREAD

**Issue by zkamvar** [grunwaldlab/poppr#172]
The current bitwise.dist() does not have the option to calculate euclidean distance. This can be done currently by converting the data to a matrix and using R's `dist()` function, but may be prohibitive on larger data sets due to memory. It may be possible to implement this relatively easily. If there is no missing data, for haploids, we simply need to take the square root of the distance. For diploids, we do the same, but we also have to ensure that the distances are squared at each locus. This will involve converting all of the 2 distances to 4. This can be done in `get_distance_custom()`:

https://github.com/grunwaldlab/poppr/blob/3994ed348d491d5c462051e737af7333da7f0073/src/bitwise_distance.c#L2130-L2145

On line 2142, if we multiply the result of `get_zeroes(ch_dist)` by 3, then it will be equivalent to squaring the distance. Here's a small proof of this in R:

``` r
M <- matrix(sample(0:2, 200, replace = TRUE), nrow = 2)
dist(M)
#>          1
#> 2 12.12436
d <- apply(M, 2, dist)
sqrt( sum(d ^ 2) )
#> [1] 12.12436
any_different <- sum(d > 0)
all_different <- sum(d > 1)
sqrt( any_different + (3 * all_different) )
#> [1] 12.12436
```

Created on 2018-02-04 by the [reprex
package](http://reprex.tidyverse.org) (v0.1.1.9000).

### Missing data

The challenge comes to what happens to missing data. The problem is that, to match R's dist() function, comparisons with missing data are re-scaled to *n(n - x)* where *n* is the number of sites and *x* is the amount of missing sites in the comparison. This will involve counting up the number of missing sites while they are being accounted for while constructing the distance. This should only involve one extra variable. 

### Tasks

 - [x] add euclidean argument to `bitwise.dist()`
 - [x] add euclidean argument to `get_distance_custom()`
 - [x] take the square root of the result (in `bitwise.dist()`)
 - [x] add counter for missing data in `bitwise_dist_haploid()` and `bitwise_dist_diploid()`

**Comment by zkamvar** [comment]
Note: here is the stackoverflow question that informed me about the scaling for missing data: https://stackoverflow.com/q/18117174/2752888

**Comment by zkamvar** [comment]
This was fixed in #176
